# -*- coding: utf-8 -*-
"""Mini-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ufxuA9L7ChhWBz0nY9kA-6oiT8ylwJWa
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="OfTfbtuqsbYVA5h9fWKC")
project = rf.workspace("project-f9w8v").project("detection-of-facilities")
version = project.version(1)
dataset = version.download("yolov8")

!pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="OfTfbtuqsbYVA5h9fWKC")
project = rf.workspace("project-f9w8v").project("detection-of-facilities")
version = project.version(2)
dataset = version.download("yolov8")

!pip install ultralytics
from IPython import display
display.clear_output()
!yolo mode=checks

from ultralytics import YOLO
from IPython.display import display, Image

!yolo task=detect mode=predict model=/content/best.pt conf=0.50 source="/content/file.jpg"

!pip install tensorflow

pip install pillow